apiVersion: apps/v1
kind: Deployment
metadata:
  name: svg-service
  namespace: apim
  labels:
    app: svg-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svg-service
  template:
    metadata:
      labels:
        app: svg-service
    spec:
      containers:
      - name: svg-service
        image: harbor.ops.action.cloudz.co.kr/apim/svg:1.0.0
        ports:
        - containerPort: 8090
        env:
        # Spring Task Execution Pool 설정
        - name: SPRING_TASK_EXECUTION_POOL_CORE_SIZE
          value: "5"
        - name: SPRING_TASK_EXECUTION_POOL_MAX_SIZE
          value: "10"
        - name: SPRING_TASK_EXECUTION_POOL_QUEUE_CAPACITY
          value: "100"
        - name: SPRING_TASK_EXECUTION_POOL_KEEP_ALIVE
          value: "60s"

        # Tomcat Thread Pool 설정
        - name: SERVER_TOMCAT_THREADS_MAX
          value: "10"
        - name: SERVER_TOMCAT_THREADS_MIN_SPARE
          value: "2"
        - name: SERVER_TOMCAT_MAX_CONNECTIONS
          value: "1000"
        - name: SERVER_TOMCAT_ACCEPT_COUNT
          value: "100"
        - name: SERVER_TOMCAT_CONNECTION_TIMEOUT
          value: "5000"

        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"

        readinessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: svg-service
  namespace: apim
spec:
  selector:
    app: svg-service
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP
