spring:
  application:
    name: svg
  task:
    execution:
      pool:
        core-size: 5         # 비동기 작업을 위한 기본 스레드 수
        max-size: 10         # 비동기 작업의 최대 스레드 수
        queue-capacity: 100  # 비동기 작업 대기 큐 크기
        keep-alive: 60s      # 추가 스레드의 유휴 시간

server:
  port: 8090
  tomcat:
    threads:
      max: 10              # 최대 worker 스레드 수 (증가)
      min-spare: 2         # 최소 유지할 idle 스레드 수 (증가)
    max-connections: 1000  # 동시에 처리할 수 있는 최대 연결 수 (증가)
    accept-count: 100       # 모든 스레드가 사용 중일 때 대기할 수 있는 요청 수
    connection-timeout: 5000 # 연결 타임아웃 (밀리초)


